### PR TITLE
Add plugin assets

### PR DESCRIPTION
**Pull request by circuitfive**
I added the three files that I was able to find in our shared directory @dimitarangelkov but I need your help to complete this PR.

See: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#default-image-sizes

* [ ] `banner-772x250.png` - this one is fine (I think)
* [ ] `banner-1544x500.png` - I was not able to find a file in our shared folder for the correct version of this image
* [ ] `icon-128x128.png` - the transparency on the corners needs to be fixed for this file
* [ ] `icon-256x256.png` - the transparency on the corners needs to be fixed for this file 
* [ ] `icon.svg` - I was not able to find a vector version of the color icon in our shared folder

### CODE REVIEW

**Comment by circuitfive** [comment]
Let's make sure that #44 gets included in this PR as well.

**Comment by royboy789** [comment]
@circuitfive - the `assets` directory they are referring to will be in the svn:

```
All files should be placed into the assets directory of your SVN directory and will work for all versions of your plugin. This is a top level directory, just like trunk
```

leaving this PR open so we can track the files. a new PR for #44 will need to be created.

**Review by dimitarangelkov — COMMENTED** [review]
I've added the missing files. @royboy789 will update the plugin WP Menu icon and then we can merge.

**Comment by circuitfive** [comment]
Thanks @dimitarangelkov these look good. I'm going to close this PR without merging, but keep the branch for later.

**Pull request closed without merging**
